config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'sessions'
  }

  devise_scope :user do
    get :signup, to: 'users/registrations#new'
    get :activate, to: 'users/confirmations#show'
  end

  resources :posts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'posts#index'
  get '/auth/:provider/callback' => 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :api, defaults: { format: :json } do
    resources :posts, only: [] do
      collection do
        get :index
        post :create
      end
      member do
        get :show
      end
    end

  end
end

app/views/layouts/_footer.html.haml
<script src="https://cdnjs.cloudflare.com/ajax/libs/iScroll/5.1.3/iscroll.min.js"></script>

app/views/layouts/_header.html.haml
.header.larger
  - if user_signed_in?
    %button.drawer-toggle.drawer-hamburger.header_humberger.visible-xs{type: "button"}
      %span.sr-only toggle navigation
      %span.drawer-hamburger-icon
    %nav.drawer-nav.header_humberger_list.visible-xs{role: "navigation"}
      %ul.drawer-menu
        %li
          = link_to root_path, class: "sidebar-list-item #{"active" if current_page?(root_path)}", 'data-no-turbolink' => true do
            .sidebar_icon
              %i.fa.fa-list-ul{"aria-hidden" => "true"}
            %span Reservations
    .logo.logo_where_header
      %a{:href => "/"} Filmo
    .header__links
      = link_to 'New Post', new_post_path, class: "header__link"
      = link_to "Log out", logout_path, method: "delete", class: "header__link"
  - else
    %button.drawer-toggle.drawer-hamburger.header_humberger.visible-xs{type: "button"}
      %span.sr-only toggle navigation
      %span.drawer-hamburger-icon
    %nav.drawer-nav.header_humberger_list.visible-xs{role: "navigation"}
      %ul.drawer-menu
        %li
          = link_to root_path, class: "sidebar-list-item #{"active" if current_page?(root_path)}", 'data-no-turbolink' => true do
            .sidebar_icon
              %i.fa.fa-list-ul{"aria-hidden" => "true"}
            %span Reservations
    .logo.logo_where_header
      %a{:href => "/"} CINELOG
    .header__links
      = link_to 'Log in', '/auth/twitter', class: "header__link"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: 'width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no', name: 'viewport'}
    %title= full_title(yield(:title))
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/drawer/3.2.0/css/drawer.min.css", :rel => "stylesheet"}/
    = stylesheet_link_tag    'application', media: 'all'
    = include_gon
    = csrf_meta_tags
  %body.drawer.drawer--left{'data-controller': controller_path, 'data-action': action_name}
    .wrapper
      = render 'layouts/header'
      #main_container.container-fluid{role: "main"}
        .row
          .col-md-offset-1.col-md-10
            .row
              - if user_signed_in?
                / = render 'layouts/sidebar'
                .col-md-12.col-sm-12#yield_layer
                  - if yield(:title) != ""
                    .page-headline
                      = yield(:title)
                  = yield
                  / = debug(params) if Rails.env.development?
              - else
                .col-md-12
                  - flash.each do |message_type, message|
                    %div{:class => "alert alert-#{message_type}"}= message
                  = yield
      = render 'layouts/footer'
    %script{src: 'https://www.gstatic.com/charts/loader.js'}
    %script{src: 'https://www.google.com/jsapi'}
    = javascript_include_tag 'application'